/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jSxoiQqAMnTEnPC4J2Lddc
// Component: 7hSxhxtE0V17

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: 6jE3Dsyufpzc/component
import Combobox from "../../Combobox"; // plasmic-import: xN73zdZC0r4i/component
import MenuItem from "../../MenuItem"; // plasmic-import: 3vE2gi5oOFPv/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectcss
import sty from "./PlasmicViewButtonPopup.module.css"; // plasmic-import: 7hSxhxtE0V17/css

import EyeIcon from "./icons/PlasmicIcon__Eye"; // plasmic-import: k2AtpvGpF7yj/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: gXJpv5gh0fGI/icon

createPlasmicElementProxy;

export type PlasmicViewButtonPopup__VariantMembers = {};
export type PlasmicViewButtonPopup__VariantsArgs = {};
type VariantPropType = keyof PlasmicViewButtonPopup__VariantsArgs;
export const PlasmicViewButtonPopup__VariantProps =
  new Array<VariantPropType>();

export type PlasmicViewButtonPopup__ArgsType = { sortBy?: string };
type ArgPropType = keyof PlasmicViewButtonPopup__ArgsType;
export const PlasmicViewButtonPopup__ArgProps = new Array<ArgPropType>(
  "sortBy"
);

export type PlasmicViewButtonPopup__OverridesType = {
  root?: Flex__<"div">;
  viewButton?: Flex__<typeof Button>;
  svg?: Flex__<"svg">;
  viewPopup?: Flex__<"div">;
  combobox?: Flex__<typeof Combobox>;
};

export interface DefaultViewButtonPopupProps {
  sortBy?: string;
  className?: string;
}

const $$ = {};

function PlasmicViewButtonPopup__RenderFunc(props: {
  variants: PlasmicViewButtonPopup__VariantsArgs;
  args: PlasmicViewButtonPopup__ArgsType;
  overrides: PlasmicViewButtonPopup__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          sortBy: "Set ID"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "combobox.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      },
      {
        path: "combobox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props["sortBy"]
      },
      {
        path: "isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <Button
        data-plasmic-name={"viewButton"}
        data-plasmic-override={overrides.viewButton}
        className={classNames("__wab_instance", sty.viewButton)}
        color={"muted"}
        iconEnd={true}
        iconStart={true}
        label={
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__sf06E
            )}
          >
            {"View"}
          </div>
        }
        onClick={async event => {
          const $steps = {};

          $steps["updateIsOpen"] = true
            ? (() => {
                const actionArgs = {
                  variable: {
                    objRoot: $state,
                    variablePath: ["isOpen"]
                  },
                  operation: 4
                };
                return (({ variable, value, startIndex, deleteCount }) => {
                  if (!variable) {
                    return;
                  }
                  const { objRoot, variablePath } = variable;

                  const oldValue = $stateGet(objRoot, variablePath);
                  $stateSet(objRoot, variablePath, !oldValue);
                  return !oldValue;
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["updateIsOpen"] != null &&
            typeof $steps["updateIsOpen"] === "object" &&
            typeof $steps["updateIsOpen"].then === "function"
          ) {
            $steps["updateIsOpen"] = await $steps["updateIsOpen"];
          }
        }}
        start={
          <EyeIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(projectcss.all, sty.svg)}
            role={"img"}
          />
        }
      />

      {(() => {
        try {
          return $state.isOpen;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <div
          data-plasmic-name={"viewPopup"}
          data-plasmic-override={overrides.viewPopup}
          className={classNames(projectcss.all, sty.viewPopup)}
          onClick={async event => {
            const $steps = {};

            $steps["updateIsOpen"] = true
              ? (() => {
                  const actionArgs = {
                    variable: {
                      objRoot: $state,
                      variablePath: ["isOpen"]
                    },
                    operation: 4
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;

                    const oldValue = $stateGet(objRoot, variablePath);
                    $stateSet(objRoot, variablePath, !oldValue);
                    return !oldValue;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateIsOpen"] != null &&
              typeof $steps["updateIsOpen"] === "object" &&
              typeof $steps["updateIsOpen"].then === "function"
            ) {
              $steps["updateIsOpen"] = await $steps["updateIsOpen"];
            }
          }}
        >
          <Combobox
            data-plasmic-name={"combobox"}
            data-plasmic-override={overrides.combobox}
            className={classNames("__wab_instance", sty.combobox)}
            isOpen={generateStateValueProp($state, ["combobox", "isOpen"])}
            items={
              <React.Fragment>
                <MenuItem label={"Set ID"} value={"Set ID"} />

                <MenuItem label={"Name: A to Z"} value={"A to Z"} />

                <MenuItem label={"Name: Z to A"} value={"Z to A"} />

                <MenuItem label={"Rarity"} value={"Rarity"} />
              </React.Fragment>
            }
            label={
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___05Dy5
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ color: "#F4F4F5" }}
                  >
                    {"Sort By"}
                  </span>
                </React.Fragment>
              </div>
            }
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["combobox", "value"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            onOpenChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["combobox", "isOpen"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            value={generateStateValueProp($state, ["combobox", "value"])}
          />
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "viewButton", "svg", "viewPopup", "combobox"],
  viewButton: ["viewButton", "svg"],
  svg: ["svg"],
  viewPopup: ["viewPopup", "combobox"],
  combobox: ["combobox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  viewButton: typeof Button;
  svg: "svg";
  viewPopup: "div";
  combobox: typeof Combobox;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicViewButtonPopup__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicViewButtonPopup__VariantsArgs;
    args?: PlasmicViewButtonPopup__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicViewButtonPopup__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicViewButtonPopup__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicViewButtonPopup__ArgProps,
          internalVariantPropNames: PlasmicViewButtonPopup__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicViewButtonPopup__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicViewButtonPopup";
  } else {
    func.displayName = `PlasmicViewButtonPopup.${nodeName}`;
  }
  return func;
}

export const PlasmicViewButtonPopup = Object.assign(
  // Top-level PlasmicViewButtonPopup renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    viewButton: makeNodeComponent("viewButton"),
    svg: makeNodeComponent("svg"),
    viewPopup: makeNodeComponent("viewPopup"),
    combobox: makeNodeComponent("combobox"),

    // Metadata about props expected for PlasmicViewButtonPopup
    internalVariantProps: PlasmicViewButtonPopup__VariantProps,
    internalArgProps: PlasmicViewButtonPopup__ArgProps
  }
);

export default PlasmicViewButtonPopup;
/* prettier-ignore-end */
