/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jSxoiQqAMnTEnPC4J2Lddc
// Component: 3IGfQBSEnDeZ

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectcss
import sty from "./PlasmicTag.module.css"; // plasmic-import: 3IGfQBSEnDeZ/css

import PublicIcon from "./icons/PlasmicIcon__Public"; // plasmic-import: evjBYq79-9w0/icon
import PrivateIcon from "./icons/PlasmicIcon__Private"; // plasmic-import: CeXR4dhh8Kee/icon

createPlasmicElementProxy;

export type PlasmicTag__VariantMembers = {
  eventStatus:
    | "registerOpen"
    | "registerClosed"
    | "registered"
    | "started"
    | "ended"
    | "webcamLive";
  deckStatus: "_public" | "_private";
};
export type PlasmicTag__VariantsArgs = {
  eventStatus?: SingleChoiceArg<
    | "registerOpen"
    | "registerClosed"
    | "registered"
    | "started"
    | "ended"
    | "webcamLive"
  >;
  deckStatus?: SingleChoiceArg<"_public" | "_private">;
};
type VariantPropType = keyof PlasmicTag__VariantsArgs;
export const PlasmicTag__VariantProps = new Array<VariantPropType>(
  "eventStatus",
  "deckStatus"
);

export type PlasmicTag__ArgsType = {};
type ArgPropType = keyof PlasmicTag__ArgsType;
export const PlasmicTag__ArgProps = new Array<ArgPropType>();

export type PlasmicTag__OverridesType = {
  tag?: Flex__<"div">;
  svg?: Flex__<"svg">;
  text?: Flex__<"div">;
};

export interface DefaultTagProps {
  eventStatus?: SingleChoiceArg<
    | "registerOpen"
    | "registerClosed"
    | "registered"
    | "started"
    | "ended"
    | "webcamLive"
  >;
  deckStatus?: SingleChoiceArg<"_public" | "_private">;
  className?: string;
}

const $$ = {};

function PlasmicTag__RenderFunc(props: {
  variants: PlasmicTag__VariantsArgs;
  args: PlasmicTag__ArgsType;
  overrides: PlasmicTag__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "eventStatus",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.eventStatus
      },
      {
        path: "deckStatus",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.deckStatus
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"tag"}
      data-plasmic-override={overrides.tag}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.tag,
        {
          [sty.tagdeckStatus__private]: hasVariant(
            $state,
            "deckStatus",
            "_private"
          ),
          [sty.tagdeckStatus__public]: hasVariant(
            $state,
            "deckStatus",
            "_public"
          ),
          [sty.tageventStatus_ended]: hasVariant(
            $state,
            "eventStatus",
            "ended"
          ),
          [sty.tageventStatus_registerClosed]: hasVariant(
            $state,
            "eventStatus",
            "registerClosed"
          ),
          [sty.tageventStatus_registerOpen]: hasVariant(
            $state,
            "eventStatus",
            "registerOpen"
          ),
          [sty.tageventStatus_started]: hasVariant(
            $state,
            "eventStatus",
            "started"
          ),
          [sty.tageventStatus_webcamLive]: hasVariant(
            $state,
            "eventStatus",
            "webcamLive"
          )
        }
      )}
      onClick={async event => {
        const $steps = {};
      }}
    >
      <PlasmicIcon__
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        PlasmicIconType={
          hasVariant($state, "deckStatus", "_private")
            ? PrivateIcon
            : PublicIcon
        }
        className={classNames(projectcss.all, sty.svg, {
          [sty.svgdeckStatus__private]: hasVariant(
            $state,
            "deckStatus",
            "_private"
          ),
          [sty.svgdeckStatus__public]: hasVariant(
            $state,
            "deckStatus",
            "_public"
          ),
          [sty.svgeventStatus_registerOpen]: hasVariant(
            $state,
            "eventStatus",
            "registerOpen"
          )
        })}
        role={"img"}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text, {
          [sty.textdeckStatus__private]: hasVariant(
            $state,
            "deckStatus",
            "_private"
          ),
          [sty.textdeckStatus__public]: hasVariant(
            $state,
            "deckStatus",
            "_public"
          ),
          [sty.texteventStatus_ended]: hasVariant(
            $state,
            "eventStatus",
            "ended"
          ),
          [sty.texteventStatus_registerClosed]: hasVariant(
            $state,
            "eventStatus",
            "registerClosed"
          ),
          [sty.texteventStatus_registerOpen]: hasVariant(
            $state,
            "eventStatus",
            "registerOpen"
          ),
          [sty.texteventStatus_started]: hasVariant(
            $state,
            "eventStatus",
            "started"
          ),
          [sty.texteventStatus_webcamLive]: hasVariant(
            $state,
            "eventStatus",
            "webcamLive"
          )
        })}
      >
        {hasVariant($state, "deckStatus", "_private") ? (
          <React.Fragment>
            <span
              className={
                "plasmic_default__all plasmic_default__span plasmic_default__span__jSxoi"
              }
              style={{ color: "#F4F4F5" }}
            >
              {"Private"}
            </span>
          </React.Fragment>
        ) : hasVariant($state, "deckStatus", "_public") ? (
          <React.Fragment>
            <span
              className={
                "plasmic_default__all plasmic_default__span plasmic_default__span__jSxoi"
              }
              style={{ color: "#F4F4F5" }}
            >
              {"Public"}
            </span>
          </React.Fragment>
        ) : hasVariant($state, "eventStatus", "webcamLive") ? (
          <React.Fragment>
            <span
              className={
                "plasmic_default__all plasmic_default__span plasmic_default__span__jSxoi"
              }
              style={{ color: "#F4F4F5" }}
            >
              {"Webcam LIVE"}
            </span>
          </React.Fragment>
        ) : hasVariant($state, "eventStatus", "ended") ? (
          <React.Fragment>
            <span
              className={
                "plasmic_default__all plasmic_default__span plasmic_default__span__jSxoi"
              }
              style={{ color: "#F4F4F5" }}
            >
              {"Event Ended"}
            </span>
          </React.Fragment>
        ) : hasVariant($state, "eventStatus", "started") ? (
          <React.Fragment>
            <span
              className={
                "plasmic_default__all plasmic_default__span plasmic_default__span__jSxoi"
              }
              style={{ color: "#F4F4F5" }}
            >
              {"Event Started"}
            </span>
          </React.Fragment>
        ) : hasVariant($state, "eventStatus", "registerClosed") ? (
          <React.Fragment>
            <span
              className={
                "plasmic_default__all plasmic_default__span plasmic_default__span__jSxoi"
              }
              style={{ color: "#F4F4F5" }}
            >
              {"Register Closed"}
            </span>
          </React.Fragment>
        ) : hasVariant($state, "eventStatus", "registerOpen") ? (
          <React.Fragment>
            <span
              className={
                "plasmic_default__all plasmic_default__span plasmic_default__span__jSxoi"
              }
              style={{ color: "#F4F4F5" }}
            >
              {"Register Open"}
            </span>
          </React.Fragment>
        ) : (
          <React.Fragment>
            <span
              className={
                "plasmic_default__all plasmic_default__span plasmic_default__span__jSxoi"
              }
              style={{ color: "#F4F4F5" }}
            >
              {"Registered"}
            </span>
          </React.Fragment>
        )}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  tag: ["tag", "svg", "text"],
  svg: ["svg"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  tag: "div";
  svg: "svg";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTag__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTag__VariantsArgs;
    args?: PlasmicTag__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTag__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTag__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTag__ArgProps,
          internalVariantPropNames: PlasmicTag__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTag__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "tag") {
    func.displayName = "PlasmicTag";
  } else {
    func.displayName = `PlasmicTag.${nodeName}`;
  }
  return func;
}

export const PlasmicTag = Object.assign(
  // Top-level PlasmicTag renders the root element
  makeNodeComponent("tag"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicTag
    internalVariantProps: PlasmicTag__VariantProps,
    internalArgProps: PlasmicTag__ArgProps
  }
);

export default PlasmicTag;
/* prettier-ignore-end */
