/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jSxoiQqAMnTEnPC4J2Lddc
// Component: xx5ugtjlJcFW

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectcss
import sty from "./PlasmicBuyMissingCards.module.css"; // plasmic-import: xx5ugtjlJcFW/css

import LeaveIcon from "./icons/PlasmicIcon__Leave"; // plasmic-import: QONxgL-Lc4xX/icon

createPlasmicElementProxy;

export type PlasmicBuyMissingCards__VariantMembers = {};
export type PlasmicBuyMissingCards__VariantsArgs = {};
type VariantPropType = keyof PlasmicBuyMissingCards__VariantsArgs;
export const PlasmicBuyMissingCards__VariantProps =
  new Array<VariantPropType>();

export type PlasmicBuyMissingCards__ArgsType = {};
type ArgPropType = keyof PlasmicBuyMissingCards__ArgsType;
export const PlasmicBuyMissingCards__ArgProps = new Array<ArgPropType>();

export type PlasmicBuyMissingCards__OverridesType = {
  buyMissingCards?: Flex__<"div">;
  missing?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultBuyMissingCardsProps {
  className?: string;
}

const $$ = {};

function PlasmicBuyMissingCards__RenderFunc(props: {
  variants: PlasmicBuyMissingCards__VariantsArgs;
  args: PlasmicBuyMissingCards__ArgsType;
  overrides: PlasmicBuyMissingCards__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"buyMissingCards"}
      data-plasmic-override={overrides.buyMissingCards}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.buyMissingCards
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text___58Dg7
        )}
      >
        {"Missing"}
      </div>
      <div
        data-plasmic-name={"missing"}
        data-plasmic-override={overrides.missing}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.missing
        )}
      >
        {"$0.00"}
      </div>
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___0I1Vx
          )}
        >
          {"Buy Cards"}
        </div>
        <LeaveIcon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg)}
          role={"img"}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  buyMissingCards: ["buyMissingCards", "missing", "freeBox", "svg"],
  missing: ["missing"],
  freeBox: ["freeBox", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  buyMissingCards: "div";
  missing: "div";
  freeBox: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBuyMissingCards__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBuyMissingCards__VariantsArgs;
    args?: PlasmicBuyMissingCards__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicBuyMissingCards__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicBuyMissingCards__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBuyMissingCards__ArgProps,
          internalVariantPropNames: PlasmicBuyMissingCards__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBuyMissingCards__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "buyMissingCards") {
    func.displayName = "PlasmicBuyMissingCards";
  } else {
    func.displayName = `PlasmicBuyMissingCards.${nodeName}`;
  }
  return func;
}

export const PlasmicBuyMissingCards = Object.assign(
  // Top-level PlasmicBuyMissingCards renders the root element
  makeNodeComponent("buyMissingCards"),
  {
    // Helper components rendering sub-elements
    missing: makeNodeComponent("missing"),
    freeBox: makeNodeComponent("freeBox"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicBuyMissingCards
    internalVariantProps: PlasmicBuyMissingCards__VariantProps,
    internalArgProps: PlasmicBuyMissingCards__ArgProps
  }
);

export default PlasmicBuyMissingCards;
/* prettier-ignore-end */
