/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jSxoiQqAMnTEnPC4J2Lddc
// Component: ZzQmP25S8p0r

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BaseSwitch } from "@plasmicpkgs/react-aria/skinny/registerSwitch";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectcss
import sty from "./PlasmicLikeSwitch.module.css"; // plasmic-import: ZzQmP25S8p0r/css

import HeartIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__Heart"; // plasmic-import: Pd6Ep5K1aJd-/icon
import HeartFilledIcon from "../library_tabler_3_2_icons/icons/PlasmicIcon__HeartFilled"; // plasmic-import: V9Lo8TsNCxdZ/icon

createPlasmicElementProxy;

export type PlasmicLikeSwitch__VariantMembers = {};
export type PlasmicLikeSwitch__VariantsArgs = {};
type VariantPropType = keyof PlasmicLikeSwitch__VariantsArgs;
export const PlasmicLikeSwitch__VariantProps = new Array<VariantPropType>();

export type PlasmicLikeSwitch__ArgsType = {
  showLabel?: boolean;
  showDescription?: boolean;
  autoFocus?: boolean;
  isSelected?: boolean;
  disabled?: boolean;
  readOnly?: boolean;
  ariaLabel?: string;
  onChange?: (val: boolean) => void;
};
type ArgPropType = keyof PlasmicLikeSwitch__ArgsType;
export const PlasmicLikeSwitch__ArgProps = new Array<ArgPropType>(
  "showLabel",
  "showDescription",
  "autoFocus",
  "isSelected",
  "disabled",
  "readOnly",
  "ariaLabel",
  "onChange"
);

export type PlasmicLikeSwitch__OverridesType = {
  ariaSwitch?: Flex__<typeof BaseSwitch>;
  freeBox?: Flex__<"div">;
  svg?: Flex__<"svg">;
  text?: Flex__<"div">;
};

export interface DefaultLikeSwitchProps {
  showLabel?: boolean;
  showDescription?: boolean;
  autoFocus?: boolean;
  isSelected?: boolean;
  disabled?: boolean;
  readOnly?: boolean;
  ariaLabel?: string;
  onChange?: (val: boolean) => void;
  className?: string;
}

const $$ = {};

function PlasmicLikeSwitch__RenderFunc(props: {
  variants: PlasmicLikeSwitch__VariantsArgs;
  args: PlasmicLikeSwitch__ArgsType;
  overrides: PlasmicLikeSwitch__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          showLabel: true,
          showDescription: false,
          autoFocus: false,
          disabled: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "ariaSwitch.isSelected",
        type: "writable",
        variableType: "boolean",

        valueProp: "isSelected",
        onChangeProp: "onChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  const [$ccVariants, setDollarCcVariants] = React.useState<
    Record<string, boolean>
  >({
    hovered: false,
    pressed: false,
    focused: false,
    focusVisible: false,
    selected: false,
    disabled: false,
    readonly: false
  });
  const updateVariant = React.useCallback(
    (changes: Record<string, boolean>) => {
      setDollarCcVariants(prev => {
        if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
          return prev;
        }
        return { ...prev, ...changes };
      });
    },
    []
  );

  return (
    <BaseSwitch
      data-plasmic-name={"ariaSwitch"}
      data-plasmic-override={overrides.ariaSwitch}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      autoFocus={args.autoFocus}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.ariaSwitch
      )}
      isDisabled={args.disabled}
      isReadOnly={args.readOnly}
      isSelected={generateStateValueProp($state, ["ariaSwitch", "isSelected"])}
      onChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, ["ariaSwitch", "isSelected"]).apply(
          null,
          eventArgs
        );
      }}
      plasmicUpdateVariant={updateVariant}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <PlasmicIcon__
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          PlasmicIconType={
            $ccVariants["selected"]
              ? HeartFilledIcon
              : $ccVariants["pressed"]
                ? HeartFilledIcon
                : HeartIcon
          }
          className={classNames(projectcss.all, sty.svg)}
          role={"img"}
        />

        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          {"0"}
        </div>
      </div>
    </BaseSwitch>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  ariaSwitch: ["ariaSwitch", "freeBox", "svg", "text"],
  freeBox: ["freeBox", "svg", "text"],
  svg: ["svg"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  ariaSwitch: typeof BaseSwitch;
  freeBox: "div";
  svg: "svg";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLikeSwitch__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLikeSwitch__VariantsArgs;
    args?: PlasmicLikeSwitch__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLikeSwitch__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLikeSwitch__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLikeSwitch__ArgProps,
          internalVariantPropNames: PlasmicLikeSwitch__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLikeSwitch__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ariaSwitch") {
    func.displayName = "PlasmicLikeSwitch";
  } else {
    func.displayName = `PlasmicLikeSwitch.${nodeName}`;
  }
  return func;
}

export const PlasmicLikeSwitch = Object.assign(
  // Top-level PlasmicLikeSwitch renders the root element
  makeNodeComponent("ariaSwitch"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicLikeSwitch
    internalVariantProps: PlasmicLikeSwitch__VariantProps,
    internalArgProps: PlasmicLikeSwitch__ArgProps
  }
);

export default PlasmicLikeSwitch;
/* prettier-ignore-end */
