/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jSxoiQqAMnTEnPC4J2Lddc
// Component: LjH9V-3dKJr5

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BaseCheckbox } from "@plasmicpkgs/react-aria/skinny/registerCheckbox";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectcss
import sty from "./PlasmicCheckbox.module.css"; // plasmic-import: LjH9V-3dKJr5/css

import CheckIcon from "./icons/PlasmicIcon__Check"; // plasmic-import: 1l2MYLOkAWrR/icon
import MinusIcon from "./icons/PlasmicIcon__Minus"; // plasmic-import: f8iR-AOO6IyV/icon

createPlasmicElementProxy;

export type PlasmicCheckbox__VariantMembers = {};
export type PlasmicCheckbox__VariantsArgs = {};
type VariantPropType = keyof PlasmicCheckbox__VariantsArgs;
export const PlasmicCheckbox__VariantProps = new Array<VariantPropType>();

export type PlasmicCheckbox__ArgsType = {
  value?: string;
  autoFocus?: boolean;
  disabled?: boolean;
  ariaLabel?: string;
  isSelected?: boolean;
  onChange?: (val: boolean) => void;
  label?: React.ReactNode;
  defaultSelected?: boolean;
};
type ArgPropType = keyof PlasmicCheckbox__ArgsType;
export const PlasmicCheckbox__ArgProps = new Array<ArgPropType>(
  "value",
  "autoFocus",
  "disabled",
  "ariaLabel",
  "isSelected",
  "onChange",
  "label",
  "defaultSelected"
);

export type PlasmicCheckbox__OverridesType = {
  ariaCheckbox?: Flex__<typeof BaseCheckbox>;
};

export interface DefaultCheckboxProps {
  value?: string;
  autoFocus?: boolean;
  disabled?: boolean;
  ariaLabel?: string;
  isSelected?: boolean;
  onChange?: (val: boolean) => void;
  label?: React.ReactNode;
  defaultSelected?: boolean;
  className?: string;
}

const $$ = {};

function PlasmicCheckbox__RenderFunc(props: {
  variants: PlasmicCheckbox__VariantsArgs;
  args: PlasmicCheckbox__ArgsType;
  overrides: PlasmicCheckbox__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          autoFocus: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "ariaCheckbox.isSelected",
        type: "writable",
        variableType: "boolean",

        valueProp: "isSelected",
        onChangeProp: "onChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  const [$ccVariants, setDollarCcVariants] = React.useState<
    Record<string, boolean>
  >({
    hovered: false,
    pressed: false,
    focused: false,
    focusVisible: false,
    indeterminate: false,
    disabled: false,
    selected: false,
    readonly: false
  });
  const updateVariant = React.useCallback(
    (changes: Record<string, boolean>) => {
      setDollarCcVariants(prev => {
        if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
          return prev;
        }
        return { ...prev, ...changes };
      });
    },
    []
  );

  return (
    <BaseCheckbox
      data-plasmic-name={"ariaCheckbox"}
      data-plasmic-override={overrides.ariaCheckbox}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      autoFocus={args.autoFocus}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.ariaCheckbox
      )}
      defaultSelected={false}
      isDisabled={args.disabled}
      isIndeterminate={$ccVariants["indeterminate"] ? true : undefined}
      isSelected={generateStateValueProp($state, [
        "ariaCheckbox",
        "isSelected"
      ])}
      onChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, ["ariaCheckbox", "isSelected"]).apply(
          null,
          eventArgs
        );
      }}
      plasmicUpdateVariant={updateVariant}
      value={args.value}
    >
      <div className={classNames(projectcss.all, sty.freeBox___8TdS7)}>
        <div className={classNames(projectcss.all, sty.freeBox__bu4LN)}>
          {(
            $ccVariants["selected"] && $ccVariants["indeterminate"]
              ? false
              : $ccVariants["selected"]
                ? true
                : false
          ) ? (
            <CheckIcon
              className={classNames(projectcss.all, sty.svg__jZkCg)}
              role={"img"}
            />
          ) : null}
          {($ccVariants["indeterminate"] ? true : false) ? (
            <MinusIcon
              className={classNames(projectcss.all, sty.svg__jm4QF)}
              role={"img"}
            />
          ) : null}
        </div>
        {renderPlasmicSlot({
          defaultContents: (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zZhKe
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "var(--token-v7qmW4z-kvLQ)" }}
                >
                  {"Option"}
                </span>
              </React.Fragment>
            </div>
          ),
          value: args.label
        })}
      </div>
    </BaseCheckbox>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  ariaCheckbox: ["ariaCheckbox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  ariaCheckbox: typeof BaseCheckbox;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCheckbox__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCheckbox__VariantsArgs;
    args?: PlasmicCheckbox__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCheckbox__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCheckbox__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCheckbox__ArgProps,
          internalVariantPropNames: PlasmicCheckbox__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCheckbox__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "ariaCheckbox") {
    func.displayName = "PlasmicCheckbox";
  } else {
    func.displayName = `PlasmicCheckbox.${nodeName}`;
  }
  return func;
}

export const PlasmicCheckbox = Object.assign(
  // Top-level PlasmicCheckbox renders the root element
  makeNodeComponent("ariaCheckbox"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCheckbox
    internalVariantProps: PlasmicCheckbox__VariantProps,
    internalArgProps: PlasmicCheckbox__ArgProps
  }
);

export default PlasmicCheckbox;
/* prettier-ignore-end */
