/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jSxoiQqAMnTEnPC4J2Lddc
// Component: peGiiJTr7MZ_

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectcss
import sty from "./PlasmicIconFilterButton.module.css"; // plasmic-import: peGiiJTr7MZ_/css

createPlasmicElementProxy;

export type PlasmicIconFilterButton__VariantMembers = {
  selected: "selected";
  iconText: "iconText";
};
export type PlasmicIconFilterButton__VariantsArgs = {
  selected?: SingleBooleanChoiceArg<"selected">;
  iconText?: SingleBooleanChoiceArg<"iconText">;
};
type VariantPropType = keyof PlasmicIconFilterButton__VariantsArgs;
export const PlasmicIconFilterButton__VariantProps = new Array<VariantPropType>(
  "selected",
  "iconText"
);

export type PlasmicIconFilterButton__ArgsType = {
  onClickyClack?: (event: any) => void;
  children?: React.ReactNode;
  slot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicIconFilterButton__ArgsType;
export const PlasmicIconFilterButton__ArgProps = new Array<ArgPropType>(
  "onClickyClack",
  "children",
  "slot"
);

export type PlasmicIconFilterButton__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
};

export interface DefaultIconFilterButtonProps {
  onClickyClack?: (event: any) => void;
  children?: React.ReactNode;
  slot?: React.ReactNode;
  selected?: SingleBooleanChoiceArg<"selected">;
  iconText?: SingleBooleanChoiceArg<"iconText">;
  className?: string;
}

const $$ = {};

function PlasmicIconFilterButton__RenderFunc(props: {
  variants: PlasmicIconFilterButton__VariantsArgs;
  args: PlasmicIconFilterButton__ArgsType;
  overrides: PlasmicIconFilterButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "selected",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.selected
      },
      {
        path: "iconText",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.iconText
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rooticonText]: hasVariant($state, "iconText", "iconText"),
          [sty.rootselected]: hasVariant($state, "selected", "selected")
        }
      )}
      onClick={args.onClickyClack}
    >
      {renderPlasmicSlot({
        defaultContents: (
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img___9QtmX)}
            displayHeight={"35px"}
            displayMaxHeight={"none"}
            displayMaxWidth={"none"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"35px"}
            loading={"lazy"}
          />
        ),

        value: args.children
      })}
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxiconText]: hasVariant($state, "iconText", "iconText")
        })}
      >
        {renderPlasmicSlot({
          defaultContents: "Enter some text",
          value: args.slot,
          className: classNames(sty.slotTargetSlot)
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicIconFilterButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicIconFilterButton__VariantsArgs;
    args?: PlasmicIconFilterButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicIconFilterButton__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicIconFilterButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicIconFilterButton__ArgProps,
          internalVariantPropNames: PlasmicIconFilterButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicIconFilterButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicIconFilterButton";
  } else {
    func.displayName = `PlasmicIconFilterButton.${nodeName}`;
  }
  return func;
}

export const PlasmicIconFilterButton = Object.assign(
  // Top-level PlasmicIconFilterButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicIconFilterButton
    internalVariantProps: PlasmicIconFilterButton__VariantProps,
    internalArgProps: PlasmicIconFilterButton__ArgProps
  }
);

export default PlasmicIconFilterButton;
/* prettier-ignore-end */
