/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jSxoiQqAMnTEnPC4J2Lddc

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsiQh7ZGberEvL } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: iQh7ZGberEvL/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsiQh7ZGberEvL
});
