/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jSxoiQqAMnTEnPC4J2Lddc
// Component: r0BetZgZ5w5v

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Tab from "../../Tab"; // plasmic-import: 8suK5OCq8JK7/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: jSxoiQqAMnTEnPC4J2Lddc/projectcss
import sty from "./PlasmicTabGroup.module.css"; // plasmic-import: r0BetZgZ5w5v/css

createPlasmicElementProxy;

export type PlasmicTabGroup__VariantMembers = {};
export type PlasmicTabGroup__VariantsArgs = {};
type VariantPropType = keyof PlasmicTabGroup__VariantsArgs;
export const PlasmicTabGroup__VariantProps = new Array<VariantPropType>();

export type PlasmicTabGroup__ArgsType = {
  tabs?: any;
  activeTab?: string;
  onActiveTabChange?: (val: string) => void;
  tabWidth?: number;
};
type ArgPropType = keyof PlasmicTabGroup__ArgsType;
export const PlasmicTabGroup__ArgProps = new Array<ArgPropType>(
  "tabs",
  "activeTab",
  "onActiveTabChange",
  "tabWidth"
);

export type PlasmicTabGroup__OverridesType = {
  root?: Flex__<"div">;
  tab?: Flex__<typeof Tab>;
};

export interface DefaultTabGroupProps {
  tabs?: any;
  activeTab?: string;
  onActiveTabChange?: (val: string) => void;
  tabWidth?: number;
  className?: string;
}

const $$ = {};

function PlasmicTabGroup__RenderFunc(props: {
  variants: PlasmicTabGroup__VariantsArgs;
  args: PlasmicTabGroup__ArgsType;
  overrides: PlasmicTabGroup__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          tabs: [
            { label: "Overview", value: "overview" },
            { label: "Details", value: "details" }
          ],
          tabWidth: 100
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "activeTab",
        type: "writable",
        variableType: "text",

        valueProp: "activeTab",
        onChangeProp: "onActiveTabChange"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
        (() => {
          try {
            return $props.tabs;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return [];
            }
            throw e;
          }
        })()
      ).map((__plasmic_item_0, __plasmic_idx_0) => {
        const currentItem = __plasmic_item_0;
        const currentIndex = __plasmic_idx_0;
        return (
          <Tab
            data-plasmic-name={"tab"}
            data-plasmic-override={overrides.tab}
            className={classNames("__wab_instance", sty.tab)}
            key={currentIndex}
            onClick={async event => {
              const $steps = {};

              $steps["updateActiveTab"] = true
                ? (() => {
                    const actionArgs = {
                      variable: {
                        objRoot: $state,
                        variablePath: ["activeTab"]
                      },
                      operation: 0,
                      value: currentItem.value
                    };
                    return (({ variable, value, startIndex, deleteCount }) => {
                      if (!variable) {
                        return;
                      }
                      const { objRoot, variablePath } = variable;

                      $stateSet(objRoot, variablePath, value);
                      return value;
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["updateActiveTab"] != null &&
                typeof $steps["updateActiveTab"] === "object" &&
                typeof $steps["updateActiveTab"].then === "function"
              ) {
                $steps["updateActiveTab"] = await $steps["updateActiveTab"];
              }
            }}
            selected={(() => {
              try {
                return $state.activeTab === currentItem.value;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return [];
                }
                throw e;
              }
            })()}
            tabName={(() => {
              try {
                return currentItem.label;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          />
        );
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "tab"],
  tab: ["tab"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  tab: typeof Tab;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTabGroup__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTabGroup__VariantsArgs;
    args?: PlasmicTabGroup__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicTabGroup__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicTabGroup__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTabGroup__ArgProps,
          internalVariantPropNames: PlasmicTabGroup__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTabGroup__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTabGroup";
  } else {
    func.displayName = `PlasmicTabGroup.${nodeName}`;
  }
  return func;
}

export const PlasmicTabGroup = Object.assign(
  // Top-level PlasmicTabGroup renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tab: makeNodeComponent("tab"),

    // Metadata about props expected for PlasmicTabGroup
    internalVariantProps: PlasmicTabGroup__VariantProps,
    internalArgProps: PlasmicTabGroup__ArgProps
  }
);

export default PlasmicTabGroup;
/* prettier-ignore-end */
