// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicAccountTab,
  DefaultAccountTabProps
} from "./plasmic/five_mics_central/PlasmicAccountTab";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { useAuth } from "@/hooks/useAuth";
import { useNavigate } from "@/router";

export interface AccountTabProps extends DefaultAccountTabProps {}

function AccountTab_(props: AccountTabProps, ref: HTMLElementRefOf<"div">) {
  const { user, signOut } = useAuth();
  const navigate = useNavigate();

  return (
    <PlasmicAccountTab
      account={{ ref }}
      {...props}
      logOutButton={{
        onClick: async () => {
          await signOut();
          navigate("/login");
        }
      }}
      profileButton={{
        label: user?.email || "Profile"
      }}
    />
  );
}

const AccountTab = React.forwardRef(AccountTab_);
export default AccountTab;
