// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicAuthentication,
  DefaultAuthenticationProps
} from "./plasmic/five_mics_central/PlasmicAuthentication";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/hooks/useAuth";
import { useNavigate } from "@/router";

export interface AuthenticationProps extends DefaultAuthenticationProps {}

function Authentication_(
  props: AuthenticationProps,
  ref: HTMLElementRefOf<"div">
) {
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [isSignUp, setIsSignUp] = React.useState(false);
  const [loading, setLoading] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const navigate = useNavigate();
  const { user, isLoading } = useAuth();

  React.useEffect(() => {
    if (!isLoading && user) {
      navigate("/player-dashboard");
    }
  }, [user, isLoading, navigate]);

  const handleEmailAuth = async () => {
    setLoading(true);
    setError(null);
    try {
      if (isSignUp) {
        const { data, error } = await supabase.auth.signUp({
          email,
          password,
        });
        if (error) throw error;
        
        if (data.session) {
          // User was automatically logged in (email confirmation likely disabled)
          navigate("/player-dashboard");
        } else {
          // User needs to confirm email
          alert("Sign up successful! Please check your email for the confirmation link before logging in.");
          // Optional: switch back to sign in mode
          setIsSignUp(false);
        }
      } else {
        const { error } = await supabase.auth.signInWithPassword({
          email,
          password,
        });
        if (error) {
          if (error.status === 400) {
            throw new Error("Invalid login credentials. Please check your email and password.");
          }
          throw error;
        }
        navigate("/player-dashboard");
      }
    } catch (e: any) {
      setError(e.message);
      alert(e.message);
    } finally {
      setLoading(false);
    }
  };

  const handleOAuth = async (provider: 'google' | 'discord') => {
    try {
      const { error } = await supabase.auth.signInWithOAuth({
        provider,
        options: {
          redirectTo: window.location.origin,
        }
      });
      if (error) throw error;
    } catch (e: any) {
      setError(e.message);
    }
  };

  return (
    <PlasmicAuthentication
      root={{ ref }}
      {...props}
      emailInput={{
        value: email,
        onChange: (v: string) => setEmail(v),
        ariaLabel: "Email"
      }}
      passwordInput={{
        value: password,
        onChange: (v: string) => setPassword(v),
        ariaLabel: "Password"
      }}
      signInButton={{
        onClick: handleEmailAuth,
        isDisabled: loading
      }}
      signUpButton={{
        onClick: handleEmailAuth,
        isDisabled: loading
      }}
      googleButton={{
        onClick: () => handleOAuth('google')
      }}
      // Note: Assuming discord button might exist or be added, 
      // for now I'll just handle google as found in PlasmicAuthentication.tsx
      signUpSwitch={{
        onClick: () => setIsSignUp(true)
      }}
      signInSwitch={{
        onClick: () => setIsSignUp(false)
      }}
    />
  );
}

const Authentication = React.forwardRef(Authentication_);
export default Authentication;
