// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicDeckCard,
  DefaultDeckCardProps
} from "./plasmic/five_mics_central/PlasmicDeckCard";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface DeckCardProps extends Omit<DefaultDeckCardProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultDeckCardProps altogether and have
// total control over the props for your component.
import { useNavigate } from "@/router";
import { Deck } from "@/lib/types";

export interface DeckCardProps extends DefaultDeckCardProps {
  deckData?: Deck;
  onClick?: () => void;
}

function DeckCard_(props: DeckCardProps, ref: HTMLElementRefOf<"div">) {
  const { deckData, onClick, ...rest } = props;
  const navigate = useNavigate();

  const handleClick = () => {
    if (onClick) {
      onClick();
    } else if (deckData) {
      navigate(`/deck-builder?id=${deckData.id}`);
    }
  };

  return (
    <PlasmicDeckCard
      deckCard={{ 
        ref,
        onClick: handleClick
      }}
      {...rest}
      deckTitle={deckData?.name || props.deckTitle}
      cardAmount={deckData?.cards.reduce((sum, c) => sum + c.quantity, 0) || props.cardAmount}
      isPublic={deckData?.is_public}
      description={deckData?.description}
      author={deckData?.author_name}
      date={deckData?.updated_at}
      styles={React.useMemo(() => {
        if (!deckData?.cards) return props.styles;
        const uniqueStyles = new Set<string>();
        deckData.cards.forEach(card => {
          // styles might be a comma-separated string or already an array
          const cardStyles = typeof card.styles === 'string' 
            ? card.styles.split(',').map(s => s.trim().toLowerCase()).filter(s => !!s)
            : [];
          cardStyles.forEach(s => uniqueStyles.add(s));
        });
        return Array.from(uniqueStyles);
      }, [deckData?.cards, props.styles])}
    />
  );
}

const DeckCard = React.forwardRef(DeckCard_);
export default DeckCard;
