// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicDeckBuilder,
  DefaultDeckBuilderProps
} from "./plasmic/fm_central/PlasmicDeckBuilder";

import { useDeckState } from '@/hooks/useDeckState';
import { useCards } from '@/hooks/useCards';
import { useCardFilters } from '@/hooks/useCardFilters';
import { useDeckStats } from '@/hooks/useDeckStats';
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import PlasmicCardComponent from "./plasmic/fm_central/PlasmicCardComponent";
import PlasmicCardFilterRow from "./plasmic/fm_central/PlasmicCardFilterRow";

export interface DeckBuilderProps extends DefaultDeckBuilderProps {}

function DeckBuilder_(props: DeckBuilderProps, ref: HTMLElementRefOf<"div">) {

    const { cards, isLoading } = useCards();
    const { deck, addCard, removeCard, setDeckName } = useDeckState();
    const {
      filters,
      setSearch,
      toggleType,
      toggleStyle,
      toggleCost,
      filteredCards,
      availableTypes,
      availableStyles,
      availableCosts,
    } = useCardFilters(cards);
    const stats = useDeckStats(deck.cards);


  if (isLoading) {
    return (
      <div style={{ padding: '2rem', textAlign: 'center' }}>
        <h2>Loading cards...</h2>
        <p>Fetching card data from Supabase</p>
      </div>
    );
  }


  
  return <PlasmicDeckBuilder availableCardsContainer={{
    children: filteredCards.slice(0,100).map((card) => 
      <PlasmicCardComponent cardName={card.name} cardStyle={card.styles[0]} 
                            cardType={card.type[0]} atkValue={card.atk?.toString()} defValue={card.def?.toString()}/>)}} 
    root={{ ref }} {...props} />;
}

const DeckBuilder = React.forwardRef(DeckBuilder_);
export default DeckBuilder;
