// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicDeckBuilder,
  DefaultDeckBuilderProps
} from "./plasmic/five_mics_central/PlasmicDeckBuilder";

import { useDeckState } from '@/hooks/useDeckState';
import { useCards } from '@/hooks/useCards';
import { useCardFilters } from '@/hooks/useCardFilters';
import { useDeckStats } from '@/hooks/useDeckStats';
import PlasmicCardComponent from "./plasmic/five_mics_central/PlasmicCard";
import PlasmicCardFilterRow from "./plasmic/fm_central/PlasmicCardFilterRow";

import { HTMLElementRefOf } from "@plasmicapp/react-web";
import IconFilterButton from "./IconFilterButton.tsx";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface DeckBuilderProps extends Omit<DefaultDeckBuilderProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultDeckBuilderProps altogether and have
// total control over the props for your component.
export interface DeckBuilderProps extends DefaultDeckBuilderProps {}

function DeckBuilder_(props: DeckBuilderProps, ref: HTMLElementRefOf<"div">) {
  const { cards, isLoading } = useCards();
  const { deck, addCard, removeCard, setDeckName } = useDeckState();
  const {
    filters,
    setSearch,
    toggleType,
    toggleStyle,
    toggleCost,
    filteredCards,
    availableTypes,
    availableStyles,
    availableCosts,
  } = useCardFilters(cards);
  const stats = useDeckStats(deck.cards);

  if (isLoading) {
    return (
        <div style={{ padding: '2rem', textAlign: 'center' }}>
          <h2>Loading cards...</h2>
          <p>Fetching card data from Supabase</p>
        </div>
    );
  }

  return <PlasmicDeckBuilder
      {...props}
      root={{ ref,
      artists: <IconFilterButton onClickyClack={ () => {console.log("artist selected");}}/>
      }}
      /*artists={{onClick: () => {console.log("artist selected")}}}*/
      /*events={{onChange: () => toggleType("events")}}
      items={{onChange: () => toggleType("items")}}*/
      availableCardsDisplayContainer={
      <PlasmicDeckBuilder.availableCardsDisplayContainer cards={{
        children: filteredCards
            .filter((card) => !!card.preview_image?.trim())
            .slice(0, 100)
            .map((card) => (
                <PlasmicCardComponent
                    isUnique={card.is_unique}
                    previewImageUrl={card.preview_image}
                    currentAmountInDeck={
                        deck.cards.find((c) => c.id === card.id)?.quantity || 0
                    }

                    plusButton={{onClick: () => addCard(card)}}
                    minusButton={{onClick: () => removeCard(card.id)}}
                />
            )),
      }}/>}

      cardsInDeck={{ children: deck.cards.map((card) => (
              <PlasmicCardComponent
                    isUnique={card.is_unique}
                    previewImageUrl={card.preview_image}
                    currentAmountInDeck={deck.cards.find((c) => c.id === card.id)?.quantity || 0}
                    plusButton={{onClick: () => addCard(card)}}
                    minusButton={{onClick: () => removeCard(card.id)}}
              />
          ))
      }}

  />;
}

const DeckBuilder = React.forwardRef(DeckBuilder_);
export default DeckBuilder;
