// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicIconFilterButton,
  DefaultIconFilterButtonProps
} from "./plasmic/five_mics_central/PlasmicIconFilterButton";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface IconFilterButtonProps extends Omit<DefaultIconFilterButtonProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultIconFilterButtonProps altogether and have
// total control over the props for your component.
export interface IconFilterButtonProps extends DefaultIconFilterButtonProps {}

function IconFilterButton_(
  props: IconFilterButtonProps,
  ref: HTMLElementRefOf<"div">
) {
  return <PlasmicIconFilterButton root={{ ref }} {...props} />;
}

const IconFilterButton = React.forwardRef(IconFilterButton_);
export default IconFilterButton;
