// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicPlayerDashboard,
  DefaultPlayerDashboardProps
} from "./plasmic/five_mics_central/PlasmicPlayerDashboard";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { useAuth } from "@/hooks/useAuth";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface PlayerDashboardProps extends Omit<DefaultPlayerDashboardProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultPlayerDashboardProps altogether and have
// total control over the props for your component.
export interface PlayerDashboardProps extends DefaultPlayerDashboardProps {}

import { supabase } from "@/lib/supabase";
import { useCards } from "@/hooks/useCards";
import { Deck, DeckCard as IDeckCard } from "@/lib/types";
import DeckCard from "./DeckCard";

function PlayerDashboard_(
  props: PlayerDashboardProps,
  ref: HTMLElementRefOf<"div">
) {
  const { user } = useAuth();
  const { cards, isLoading: cardsLoading } = useCards();
  const [userDecks, setUserDecks] = React.useState<Deck[]>([]);
  const [isDecksLoading, setIsDecksLoading] = React.useState(true);

  React.useEffect(() => {
    const fetchUserDecks = async () => {
      if (!user) {
        setIsDecksLoading(false);
        return;
      }
      
      setIsDecksLoading(true);
      console.log("[FETCH] Starting deck fetch for user:", user.id);
      try {
        // 1. Fetch decks metadata
        const { data: decksRows, error: decksError } = await supabase
          .from('decks')
          .select('*')
          .eq('user_id', user.id)
          .order('updated_at', { ascending: false });

        if (decksError) throw decksError;

        console.log("[FETCH] Decks metadata fetched:", decksRows?.length);

        // 2. Fetch all cards for these decks
        const deckIds = decksRows.map(d => d.id);
        if (deckIds.length === 0) {
          console.log("[FETCH] No decks found for user");
          setUserDecks([]);
          setIsDecksLoading(false);
          return;
        }

        const { data: deckCardsRows, error: deckCardsError } = await supabase
          .from('deck_cards')
          .select('*')
          .in('deck_id', deckIds);

        if (deckCardsError) throw deckCardsError;
        console.log("[FETCH] Deck cards fetched:", deckCardsRows?.length);

        // 3. Assemble full Deck objects
        const assembledDecks: Deck[] = decksRows.map(deckRow => {
          const cardsInDeck: IDeckCard[] = deckCardsRows
            .filter(dc => dc.deck_id === deckRow.id)
            .map(dc => {
              const cardInfo = cards.find(c => c.id === dc.card_id);
              return {
                ...(cardInfo || { id: dc.card_id, name: 'Unknown Card' } as any),
                quantity: dc.quantity
              };
            })
            .filter(c => !!c.id);

          return {
            id: deckRow.id,
            user_id: deckRow.user_id,
            name: deckRow.name,
            description: deckRow.description || "",
            is_public: deckRow.is_public,
            author_name: deckRow.author_name || "",
            format: deckRow.format,
            cards: cardsInDeck,
            created_at: new Date(deckRow.created_at),
            updated_at: new Date(deckRow.updated_at)
          };
        });
        
        console.log('[FETCH] Setting userDecks with length:', assembledDecks.length);
        setUserDecks(assembledDecks);
        // Ensure state update is seen
        setTimeout(() => {
          console.log('[FETCH] Setting isDecksLoading to false');
          setIsDecksLoading(false);
        }, 0);
      } catch (err: any) {
        console.error("[FETCH] Error fetching user decks:", err.message);
        setIsDecksLoading(false);
      }
    };

    fetchUserDecks();
  }, [user, cards]);

  console.log('Rendering PlayerDashboard with state:', { isDecksLoading, cardsLoading, userDecksLength: userDecks.length });

  // Use a simple array if not loading and has decks
  const decksGridContent = (isDecksLoading || (cardsLoading && userDecks.length === 0)) ? (
    <div key="loading" style={{ padding: '20px', color: 'white', width: '100%' }}>
      Loading decks (isDecksLoading: {String(isDecksLoading)}, cardsLoading: {String(cardsLoading)}, userDecks: {userDecks.length})...
    </div>
  ) : userDecks.length === 0 ? (
    <div key="empty" style={{ padding: '20px', color: 'white', width: '100%' }}>
      No decks found. Save some decks in the deck builder!
    </div>
  ) : (
    userDecks.map(deck => (
      <DeckCard 
        key={deck.id}
        deckData={deck}
      />
    ))
  );

  console.log('Final decksGridContent:', decksGridContent);

  return (
    <PlasmicPlayerDashboard
      root={{ ref }}
      {...props}
      username={{
        children: user?.email || "Guest"
      }}
      deckGrid={{
        children: decksGridContent,
        "data-test-id": "deck-grid-override"
      }}
      userId={{
        ariaLabel: "User ID"
      }}
    />
  );
}

const PlayerDashboard = React.forwardRef(PlayerDashboard_);
export default PlayerDashboard;
