/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2z3i9W46Zy1LESdTeBafaW
// Component: DDGVTTPZXDNs

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextInput from "../../TextInput"; // plasmic-import: bTOD0F4HyKA7/component
import CardFilterRow from "../../CardFilterRow"; // plasmic-import: IHyN_TrhzrMA/component
import CardComponent from "../../CardComponent"; // plasmic-import: RoBCNbzUQdAH/component
import Switch from "../../Switch"; // plasmic-import: oCJNC8dAmvaF/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 2z3i9W46Zy1LESdTeBafaW/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 2z3i9W46Zy1LESdTeBafaW/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2z3i9W46Zy1LESdTeBafaW/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: DDGVTTPZXDNs/css

import NounSearch7640330SvgIcon from "./icons/PlasmicIcon__NounSearch7640330Svg"; // plasmic-import: oJpROMdnscqZ/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  section?: Flex__<"section">;
  svg?: Flex__<"svg">;
  textInput?: Flex__<typeof TextInput>;
  cardFilterRow?: Flex__<typeof CardFilterRow>;
  availableCardsContainer?: Flex__<"div">;
  cardComponent?: Flex__<typeof CardComponent>;
  deckName?: Flex__<"div">;
  deckStatsContainer?: Flex__<"div">;
  _switch?: Flex__<typeof Switch>;
  viewChangeContainer?: Flex__<"div">;
  switch2?: Flex__<typeof Switch>;
  deckCardsContainer?: Flex__<"div">;
  helloWorld?: Flex__<"div">;
};

export interface DefaultHomepageProps {
  className?: string;
}

const $$ = {};

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "_switch.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "switch2.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__twyoC)}>
            <section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames(projectcss.all, sty.section)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__lzKN)}>
                <div className={classNames(projectcss.all, sty.freeBox__ifLgY)}>
                  <NounSearch7640330SvgIcon
                    data-plasmic-name={"svg"}
                    data-plasmic-override={overrides.svg}
                    className={classNames(projectcss.all, sty.svg)}
                    role={"img"}
                  />

                  <TextInput
                    data-plasmic-name={"textInput"}
                    data-plasmic-override={overrides.textInput}
                    ariaLabel={"search"}
                    className={classNames("__wab_instance", sty.textInput)}
                    onChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "textInput",
                        "value"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                    placeholder={"search"}
                    value={generateStateValueProp($state, [
                      "textInput",
                      "value"
                    ])}
                  />
                </div>
                <CardFilterRow
                  data-plasmic-name={"cardFilterRow"}
                  data-plasmic-override={overrides.cardFilterRow}
                  className={classNames("__wab_instance", sty.cardFilterRow)}
                />
              </div>
              <div
                data-plasmic-name={"availableCardsContainer"}
                data-plasmic-override={overrides.availableCardsContainer}
                className={classNames(
                  projectcss.all,
                  sty.availableCardsContainer
                )}
              >
                <CardComponent
                  data-plasmic-name={"cardComponent"}
                  data-plasmic-override={overrides.cardComponent}
                  className={classNames("__wab_instance", sty.cardComponent)}
                />
              </div>
            </section>
            <div className={classNames(projectcss.all, sty.freeBox__wkcQf)}>
              <div className={classNames(projectcss.all, sty.freeBox___9FZum)}>
                <div
                  data-plasmic-name={"deckName"}
                  data-plasmic-override={overrides.deckName}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.deckName
                  )}
                >
                  {"Unsaved Deck"}
                </div>
                <div
                  data-plasmic-name={"deckStatsContainer"}
                  data-plasmic-override={overrides.deckStatsContainer}
                  className={classNames(projectcss.all, sty.deckStatsContainer)}
                >
                  <Switch
                    data-plasmic-name={"_switch"}
                    data-plasmic-override={overrides._switch}
                    className={classNames("__wab_instance", sty._switch)}
                    isSelected={generateStateValueProp($state, [
                      "_switch",
                      "isSelected"
                    ])}
                    onChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "_switch",
                        "isSelected"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                  />
                </div>
                <div
                  data-plasmic-name={"viewChangeContainer"}
                  data-plasmic-override={overrides.viewChangeContainer}
                  className={classNames(
                    projectcss.all,
                    sty.viewChangeContainer
                  )}
                >
                  <Switch
                    data-plasmic-name={"switch2"}
                    data-plasmic-override={overrides.switch2}
                    className={classNames("__wab_instance", sty.switch2)}
                    isSelected={generateStateValueProp($state, [
                      "switch2",
                      "isSelected"
                    ])}
                    onChange={async (...eventArgs: any) => {
                      generateStateOnChangeProp($state, [
                        "switch2",
                        "isSelected"
                      ]).apply(null, eventArgs);

                      if (
                        eventArgs.length > 1 &&
                        eventArgs[1] &&
                        eventArgs[1]._plasmic_state_init_
                      ) {
                        return;
                      }
                    }}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"deckCardsContainer"}
                data-plasmic-override={overrides.deckCardsContainer}
                className={classNames(projectcss.all, sty.deckCardsContainer)}
              />
            </div>
          </div>
          <div
            data-plasmic-name={"helloWorld"}
            data-plasmic-override={overrides.helloWorld}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.helloWorld
            )}
          >
            {"TEMPORARY TITLE FOR HOME PAGE"}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "section",
    "svg",
    "textInput",
    "cardFilterRow",
    "availableCardsContainer",
    "cardComponent",
    "deckName",
    "deckStatsContainer",
    "_switch",
    "viewChangeContainer",
    "switch2",
    "deckCardsContainer",
    "helloWorld"
  ],
  section: [
    "section",
    "svg",
    "textInput",
    "cardFilterRow",
    "availableCardsContainer",
    "cardComponent"
  ],
  svg: ["svg"],
  textInput: ["textInput"],
  cardFilterRow: ["cardFilterRow"],
  availableCardsContainer: ["availableCardsContainer", "cardComponent"],
  cardComponent: ["cardComponent"],
  deckName: ["deckName"],
  deckStatsContainer: ["deckStatsContainer", "_switch"],
  _switch: ["_switch"],
  viewChangeContainer: ["viewChangeContainer", "switch2"],
  switch2: ["switch2"],
  deckCardsContainer: ["deckCardsContainer"],
  helloWorld: ["helloWorld"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  section: "section";
  svg: "svg";
  textInput: typeof TextInput;
  cardFilterRow: typeof CardFilterRow;
  availableCardsContainer: "div";
  cardComponent: typeof CardComponent;
  deckName: "div";
  deckStatsContainer: "div";
  _switch: typeof Switch;
  viewChangeContainer: "div";
  switch2: typeof Switch;
  deckCardsContainer: "div";
  helloWorld: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    svg: makeNodeComponent("svg"),
    textInput: makeNodeComponent("textInput"),
    cardFilterRow: makeNodeComponent("cardFilterRow"),
    availableCardsContainer: makeNodeComponent("availableCardsContainer"),
    cardComponent: makeNodeComponent("cardComponent"),
    deckName: makeNodeComponent("deckName"),
    deckStatsContainer: makeNodeComponent("deckStatsContainer"),
    _switch: makeNodeComponent("_switch"),
    viewChangeContainer: makeNodeComponent("viewChangeContainer"),
    switch2: makeNodeComponent("switch2"),
    deckCardsContainer: makeNodeComponent("deckCardsContainer"),
    helloWorld: makeNodeComponent("helloWorld"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Home",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
