/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2z3i9W46Zy1LESdTeBafaW
// Component: RoBCNbzUQdAH

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 2z3i9W46Zy1LESdTeBafaW/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 2z3i9W46Zy1LESdTeBafaW/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2z3i9W46Zy1LESdTeBafaW/projectcss
import sty from "./PlasmicCardComponent.module.css"; // plasmic-import: RoBCNbzUQdAH/css

createPlasmicElementProxy;

export type PlasmicCardComponent__VariantMembers = {};
export type PlasmicCardComponent__VariantsArgs = {};
type VariantPropType = keyof PlasmicCardComponent__VariantsArgs;
export const PlasmicCardComponent__VariantProps = new Array<VariantPropType>();

export type PlasmicCardComponent__ArgsType = {
  cardName?: string;
  cardType?: string;
  cardStyle?: string;
  atkValue?: string;
  defValue?: string;
};
type ArgPropType = keyof PlasmicCardComponent__ArgsType;
export const PlasmicCardComponent__ArgProps = new Array<ArgPropType>(
  "cardName",
  "cardType",
  "cardStyle",
  "atkValue",
  "defValue"
);

export type PlasmicCardComponent__OverridesType = {
  cardContainer?: Flex__<"div">;
  cardContent?: Flex__<"div">;
  name?: Flex__<"div">;
  type?: Flex__<"div">;
  cardStyleText?: Flex__<"div">;
  attackValue?: Flex__<"div">;
  defenseValue?: Flex__<"div">;
};

export interface DefaultCardComponentProps {
  cardName?: string;
  cardType?: string;
  cardStyle?: string;
  atkValue?: string;
  defValue?: string;
  className?: string;
}

const $$ = {};

function PlasmicCardComponent__RenderFunc(props: {
  variants: PlasmicCardComponent__VariantsArgs;
  args: PlasmicCardComponent__ArgsType;
  overrides: PlasmicCardComponent__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          cardName: "Placeholder Name",
          cardType: "Type",
          cardStyle: "Style",
          atkValue: "1",
          defValue: "2"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"cardContainer"}
      data-plasmic-override={overrides.cardContainer}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.cardContainer
      )}
    >
      <div
        data-plasmic-name={"cardContent"}
        data-plasmic-override={overrides.cardContent}
        className={classNames(projectcss.all, sty.cardContent)}
      >
        <div
          data-plasmic-name={"name"}
          data-plasmic-override={overrides.name}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.name
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.cardName;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "Card Name";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
        <div
          data-plasmic-name={"type"}
          data-plasmic-override={overrides.type}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.type
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.cardType;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "Card Type";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
        <div
          data-plasmic-name={"cardStyleText"}
          data-plasmic-override={overrides.cardStyleText}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.cardStyleText
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.cardStyle;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "Style";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
        <div
          data-plasmic-name={"attackValue"}
          data-plasmic-override={overrides.attackValue}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.attackValue
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.atkValue;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "Attack";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
        <div
          data-plasmic-name={"defenseValue"}
          data-plasmic-override={overrides.defenseValue}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.defenseValue
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.defValue;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "Defense";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  cardContainer: [
    "cardContainer",
    "cardContent",
    "name",
    "type",
    "cardStyleText",
    "attackValue",
    "defenseValue"
  ],
  cardContent: [
    "cardContent",
    "name",
    "type",
    "cardStyleText",
    "attackValue",
    "defenseValue"
  ],
  name: ["name"],
  type: ["type"],
  cardStyleText: ["cardStyleText"],
  attackValue: ["attackValue"],
  defenseValue: ["defenseValue"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  cardContainer: "div";
  cardContent: "div";
  name: "div";
  type: "div";
  cardStyleText: "div";
  attackValue: "div";
  defenseValue: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCardComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCardComponent__VariantsArgs;
    args?: PlasmicCardComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCardComponent__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCardComponent__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardComponent__ArgProps,
          internalVariantPropNames: PlasmicCardComponent__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "cardContainer") {
    func.displayName = "PlasmicCardComponent";
  } else {
    func.displayName = `PlasmicCardComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicCardComponent = Object.assign(
  // Top-level PlasmicCardComponent renders the root element
  makeNodeComponent("cardContainer"),
  {
    // Helper components rendering sub-elements
    cardContent: makeNodeComponent("cardContent"),
    _name: makeNodeComponent("name"),
    type: makeNodeComponent("type"),
    cardStyleText: makeNodeComponent("cardStyleText"),
    attackValue: makeNodeComponent("attackValue"),
    defenseValue: makeNodeComponent("defenseValue"),

    // Metadata about props expected for PlasmicCardComponent
    internalVariantProps: PlasmicCardComponent__VariantProps,
    internalArgProps: PlasmicCardComponent__ArgProps
  }
);

export default PlasmicCardComponent;
/* prettier-ignore-end */
