/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2z3i9W46Zy1LESdTeBafaW
// Component: IHyN_TrhzrMA

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Checkbox from "../../Checkbox"; // plasmic-import: 7KtYPL8xZXmj/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 2z3i9W46Zy1LESdTeBafaW/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 2z3i9W46Zy1LESdTeBafaW/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 2z3i9W46Zy1LESdTeBafaW/projectcss
import sty from "./PlasmicCardFilterRow.module.css"; // plasmic-import: IHyN_TrhzrMA/css

createPlasmicElementProxy;

export type PlasmicCardFilterRow__VariantMembers = {};
export type PlasmicCardFilterRow__VariantsArgs = {};
type VariantPropType = keyof PlasmicCardFilterRow__VariantsArgs;
export const PlasmicCardFilterRow__VariantProps = new Array<VariantPropType>();

export type PlasmicCardFilterRow__ArgsType = {};
type ArgPropType = keyof PlasmicCardFilterRow__ArgsType;
export const PlasmicCardFilterRow__ArgProps = new Array<ArgPropType>();

export type PlasmicCardFilterRow__OverridesType = {
  root?: Flex__<"div">;
  cardTypeFilters?: Flex__<"div">;
  aritstFilterToggle?: Flex__<typeof Checkbox>;
  itemFilterToggle?: Flex__<typeof Checkbox>;
  eventFilterToggle?: Flex__<typeof Checkbox>;
  styleFilters?: Flex__<"div">;
  chillFilter?: Flex__<typeof Checkbox>;
  emoFilter?: Flex__<typeof Checkbox>;
  partyFilter?: Flex__<typeof Checkbox>;
  consciousFilter?: Flex__<typeof Checkbox>;
  hardcoreFilter?: Flex__<typeof Checkbox>;
  costFilters?: Flex__<"div">;
  filter0?: Flex__<typeof Checkbox>;
  filter1?: Flex__<typeof Checkbox>;
  filter12?: Flex__<typeof Checkbox>;
  filter13?: Flex__<typeof Checkbox>;
  filter14?: Flex__<typeof Checkbox>;
  filter15?: Flex__<typeof Checkbox>;
  filter16?: Flex__<typeof Checkbox>;
  filter17?: Flex__<typeof Checkbox>;
  filter18?: Flex__<typeof Checkbox>;
};

export interface DefaultCardFilterRowProps {
  className?: string;
}

const $$ = {};

function PlasmicCardFilterRow__RenderFunc(props: {
  variants: PlasmicCardFilterRow__VariantsArgs;
  args: PlasmicCardFilterRow__ArgsType;
  overrides: PlasmicCardFilterRow__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "aritstFilterToggle.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "itemFilterToggle.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "eventFilterToggle.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "chillFilter.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "emoFilter.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "partyFilter.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "consciousFilter.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "hardcoreFilter.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "filter0.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "filter1.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "filter12.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "filter13.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "filter14.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "filter15.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "filter16.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "filter17.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "filter18.isSelected",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"cardTypeFilters"}
        data-plasmic-override={overrides.cardTypeFilters}
        className={classNames(projectcss.all, sty.cardTypeFilters)}
      >
        <Checkbox
          data-plasmic-name={"aritstFilterToggle"}
          data-plasmic-override={overrides.aritstFilterToggle}
          className={classNames("__wab_instance", sty.aritstFilterToggle)}
          isSelected={generateStateValueProp($state, [
            "aritstFilterToggle",
            "isSelected"
          ])}
          label={"Artist"}
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "aritstFilterToggle",
              "isSelected"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"itemFilterToggle"}
          data-plasmic-override={overrides.itemFilterToggle}
          className={classNames("__wab_instance", sty.itemFilterToggle)}
          isSelected={generateStateValueProp($state, [
            "itemFilterToggle",
            "isSelected"
          ])}
          label={"Item"}
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "itemFilterToggle",
              "isSelected"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"eventFilterToggle"}
          data-plasmic-override={overrides.eventFilterToggle}
          className={classNames("__wab_instance", sty.eventFilterToggle)}
          isSelected={generateStateValueProp($state, [
            "eventFilterToggle",
            "isSelected"
          ])}
          label={"Event"}
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "eventFilterToggle",
              "isSelected"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />
      </div>
      <div
        data-plasmic-name={"styleFilters"}
        data-plasmic-override={overrides.styleFilters}
        className={classNames(projectcss.all, sty.styleFilters)}
      >
        <Checkbox
          data-plasmic-name={"chillFilter"}
          data-plasmic-override={overrides.chillFilter}
          className={classNames("__wab_instance", sty.chillFilter)}
          isSelected={generateStateValueProp($state, [
            "chillFilter",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xjq0
              )}
            >
              {"Chill"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "chillFilter",
              "isSelected"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"emoFilter"}
          data-plasmic-override={overrides.emoFilter}
          className={classNames("__wab_instance", sty.emoFilter)}
          isSelected={generateStateValueProp($state, [
            "emoFilter",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1TJf0
              )}
            >
              {"Emo"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "emoFilter",
              "isSelected"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"partyFilter"}
          data-plasmic-override={overrides.partyFilter}
          className={classNames("__wab_instance", sty.partyFilter)}
          isSelected={generateStateValueProp($state, [
            "partyFilter",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jNaAq
              )}
            >
              {"Party"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "partyFilter",
              "isSelected"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"consciousFilter"}
          data-plasmic-override={overrides.consciousFilter}
          className={classNames("__wab_instance", sty.consciousFilter)}
          isSelected={generateStateValueProp($state, [
            "consciousFilter",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__us3Na
              )}
            >
              {"Conscious"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "consciousFilter",
              "isSelected"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"hardcoreFilter"}
          data-plasmic-override={overrides.hardcoreFilter}
          className={classNames("__wab_instance", sty.hardcoreFilter)}
          isSelected={generateStateValueProp($state, [
            "hardcoreFilter",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__r2Xfx
              )}
            >
              {"Hardcore"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, [
              "hardcoreFilter",
              "isSelected"
            ]).apply(null, eventArgs);

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />
      </div>
      <div
        data-plasmic-name={"costFilters"}
        data-plasmic-override={overrides.costFilters}
        className={classNames(projectcss.all, sty.costFilters)}
      >
        <Checkbox
          data-plasmic-name={"filter0"}
          data-plasmic-override={overrides.filter0}
          className={classNames("__wab_instance", sty.filter0)}
          isSelected={generateStateValueProp($state, ["filter0", "isSelected"])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lp4Jr
              )}
            >
              {"0"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["filter0", "isSelected"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"filter1"}
          data-plasmic-override={overrides.filter1}
          className={classNames("__wab_instance", sty.filter1)}
          isSelected={generateStateValueProp($state, ["filter1", "isSelected"])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oziH1
              )}
            >
              {"1"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["filter1", "isSelected"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"filter12"}
          data-plasmic-override={overrides.filter12}
          className={classNames("__wab_instance", sty.filter12)}
          isSelected={generateStateValueProp($state, [
            "filter12",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__mV5I5
              )}
            >
              {"2"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["filter12", "isSelected"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"filter13"}
          data-plasmic-override={overrides.filter13}
          className={classNames("__wab_instance", sty.filter13)}
          isSelected={generateStateValueProp($state, [
            "filter13",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9Fkdz
              )}
            >
              {"3"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["filter13", "isSelected"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"filter14"}
          data-plasmic-override={overrides.filter14}
          className={classNames("__wab_instance", sty.filter14)}
          isSelected={generateStateValueProp($state, [
            "filter14",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__wvDMw
              )}
            >
              {"4"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["filter14", "isSelected"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"filter15"}
          data-plasmic-override={overrides.filter15}
          className={classNames("__wab_instance", sty.filter15)}
          isSelected={generateStateValueProp($state, [
            "filter15",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___7PhXv
              )}
            >
              {"5"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["filter15", "isSelected"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"filter16"}
          data-plasmic-override={overrides.filter16}
          className={classNames("__wab_instance", sty.filter16)}
          isSelected={generateStateValueProp($state, [
            "filter16",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__k9Gwa
              )}
            >
              {"6"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["filter16", "isSelected"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"filter17"}
          data-plasmic-override={overrides.filter17}
          className={classNames("__wab_instance", sty.filter17)}
          isSelected={generateStateValueProp($state, [
            "filter17",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___3I7AM
              )}
            >
              {"7"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["filter17", "isSelected"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />

        <Checkbox
          data-plasmic-name={"filter18"}
          data-plasmic-override={overrides.filter18}
          className={classNames("__wab_instance", sty.filter18)}
          isSelected={generateStateValueProp($state, [
            "filter18",
            "isSelected"
          ])}
          label={
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___9Mpgn
              )}
            >
              {"8"}
            </div>
          }
          onChange={async (...eventArgs: any) => {
            generateStateOnChangeProp($state, ["filter18", "isSelected"]).apply(
              null,
              eventArgs
            );

            if (
              eventArgs.length > 1 &&
              eventArgs[1] &&
              eventArgs[1]._plasmic_state_init_
            ) {
              return;
            }
          }}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "cardTypeFilters",
    "aritstFilterToggle",
    "itemFilterToggle",
    "eventFilterToggle",
    "styleFilters",
    "chillFilter",
    "emoFilter",
    "partyFilter",
    "consciousFilter",
    "hardcoreFilter",
    "costFilters",
    "filter0",
    "filter1",
    "filter12",
    "filter13",
    "filter14",
    "filter15",
    "filter16",
    "filter17",
    "filter18"
  ],
  cardTypeFilters: [
    "cardTypeFilters",
    "aritstFilterToggle",
    "itemFilterToggle",
    "eventFilterToggle"
  ],
  aritstFilterToggle: ["aritstFilterToggle"],
  itemFilterToggle: ["itemFilterToggle"],
  eventFilterToggle: ["eventFilterToggle"],
  styleFilters: [
    "styleFilters",
    "chillFilter",
    "emoFilter",
    "partyFilter",
    "consciousFilter",
    "hardcoreFilter"
  ],
  chillFilter: ["chillFilter"],
  emoFilter: ["emoFilter"],
  partyFilter: ["partyFilter"],
  consciousFilter: ["consciousFilter"],
  hardcoreFilter: ["hardcoreFilter"],
  costFilters: [
    "costFilters",
    "filter0",
    "filter1",
    "filter12",
    "filter13",
    "filter14",
    "filter15",
    "filter16",
    "filter17",
    "filter18"
  ],
  filter0: ["filter0"],
  filter1: ["filter1"],
  filter12: ["filter12"],
  filter13: ["filter13"],
  filter14: ["filter14"],
  filter15: ["filter15"],
  filter16: ["filter16"],
  filter17: ["filter17"],
  filter18: ["filter18"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  cardTypeFilters: "div";
  aritstFilterToggle: typeof Checkbox;
  itemFilterToggle: typeof Checkbox;
  eventFilterToggle: typeof Checkbox;
  styleFilters: "div";
  chillFilter: typeof Checkbox;
  emoFilter: typeof Checkbox;
  partyFilter: typeof Checkbox;
  consciousFilter: typeof Checkbox;
  hardcoreFilter: typeof Checkbox;
  costFilters: "div";
  filter0: typeof Checkbox;
  filter1: typeof Checkbox;
  filter12: typeof Checkbox;
  filter13: typeof Checkbox;
  filter14: typeof Checkbox;
  filter15: typeof Checkbox;
  filter16: typeof Checkbox;
  filter17: typeof Checkbox;
  filter18: typeof Checkbox;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCardFilterRow__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCardFilterRow__VariantsArgs;
    args?: PlasmicCardFilterRow__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCardFilterRow__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCardFilterRow__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCardFilterRow__ArgProps,
          internalVariantPropNames: PlasmicCardFilterRow__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCardFilterRow__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardFilterRow";
  } else {
    func.displayName = `PlasmicCardFilterRow.${nodeName}`;
  }
  return func;
}

export const PlasmicCardFilterRow = Object.assign(
  // Top-level PlasmicCardFilterRow renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cardTypeFilters: makeNodeComponent("cardTypeFilters"),
    aritstFilterToggle: makeNodeComponent("aritstFilterToggle"),
    itemFilterToggle: makeNodeComponent("itemFilterToggle"),
    eventFilterToggle: makeNodeComponent("eventFilterToggle"),
    styleFilters: makeNodeComponent("styleFilters"),
    chillFilter: makeNodeComponent("chillFilter"),
    emoFilter: makeNodeComponent("emoFilter"),
    partyFilter: makeNodeComponent("partyFilter"),
    consciousFilter: makeNodeComponent("consciousFilter"),
    hardcoreFilter: makeNodeComponent("hardcoreFilter"),
    costFilters: makeNodeComponent("costFilters"),
    filter0: makeNodeComponent("filter0"),
    filter1: makeNodeComponent("filter1"),
    filter12: makeNodeComponent("filter12"),
    filter13: makeNodeComponent("filter13"),
    filter14: makeNodeComponent("filter14"),
    filter15: makeNodeComponent("filter15"),
    filter16: makeNodeComponent("filter16"),
    filter17: makeNodeComponent("filter17"),
    filter18: makeNodeComponent("filter18"),

    // Metadata about props expected for PlasmicCardFilterRow
    internalVariantProps: PlasmicCardFilterRow__VariantProps,
    internalArgProps: PlasmicCardFilterRow__ArgProps
  }
);

export default PlasmicCardFilterRow;
/* prettier-ignore-end */
